spring.application.name=JPASpringBootProject

spring.datasource.url=jdbc:mysql://localhost:3306/testdb

spring.datasource.username=root
spring.datasource.password=kartik07
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

# Enable caching
spring.cache.type=redis
spring.cache.redis.time-to-live=600000 #10 minute
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=jpaapp:

spring.docker.compose.enabled=true
